### ISSUE TITLE
CloudFlare IPs Out Of Date

### ISSUE THREAD

**Issue by IsaiahJTurner** [Mewte/cloudflare-express#1]
See [IsaiahJTurner/cloudflare-express](/IsaiahJTurner/cloudflare-express) for a potential long term solution.

**Comment by Mewte** [comment]
I created a pull request and I'll be looking through the changes.

Thanks for the improvements :) I haven't really messed with this project in a while.

**Comment by Mewte** [comment]
Fixed by using .restore({update_on_start:true}) in latest release

also IP list has been updated.
