### ISSUE TITLE
Seems not to be working 

### ISSUE THREAD

**Issue by serganus** [Mewte/cloudflare-express#5]
`req.ip` and `req.cf_ip` both have the same values. I think they should be different? Pls correct me if I am wrong. Thanks

![screen shot 2017-01-13 at 3 17 36 pm](https://cloud.githubusercontent.com/assets/12946435/21921616/4fc259a6-d9a4-11e6-94fb-14d7e56d5952.png)

I am using as a middleware before any other middleware.

**Comment by Mewte** [comment]
fixed by #4, thank you @joostdebruijn
