### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by Fenny** [Mewte/cloudflare-express#8]
Hey,

Can I ask why you need the CF ip range in this module?
Can't you just check if cf-connecting-ip header is present?

// middleware
if (req.headers['cf-connecting-ip']) {
   req.ip = req.headers['cf-connecting-ip']
}

**Comment by Mewte** [comment]
Hi Jad3z,

Unfortunately if you only check that the header is present and don't validate that the remote connection is coming from Cloudflare, anyone could put any value they want for the cf-connecting-ip header when making a request. The IP range allows you to verify that the connection is coming from Cloudflare so the cf-connecting-ip is trustworthy and the users actual IP address.

**Comment by Fenny** [comment]
@Mewte Makes sense, thank you!
